// Generated by gencpp from file irp_sen_msgs/encoder.msg
// DO NOT EDIT!


#ifndef IRP_SEN_MSGS_MESSAGE_ENCODER_H
#define IRP_SEN_MSGS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace irp_sen_msgs
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : header()
    , type(0)
    , left_count(0)
    , right_count(0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , left_count(0)
    , right_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _type_type;
  _type_type type;

   typedef int64_t _left_count_type;
  _left_count_type left_count;

   typedef int64_t _right_count_type;
  _right_count_type right_count;





  typedef boost::shared_ptr< ::irp_sen_msgs::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irp_sen_msgs::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::irp_sen_msgs::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::irp_sen_msgs::encoder > encoderPtr;
typedef boost::shared_ptr< ::irp_sen_msgs::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irp_sen_msgs::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irp_sen_msgs::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::irp_sen_msgs::encoder_<ContainerAllocator1> & lhs, const ::irp_sen_msgs::encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.left_count == rhs.left_count &&
    lhs.right_count == rhs.right_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::irp_sen_msgs::encoder_<ContainerAllocator1> & lhs, const ::irp_sen_msgs::encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace irp_sen_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::irp_sen_msgs::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irp_sen_msgs::encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irp_sen_msgs::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irp_sen_msgs::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irp_sen_msgs::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irp_sen_msgs::encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irp_sen_msgs::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "360abb290fcf41163977621351ecd430";
  }

  static const char* value(const ::irp_sen_msgs::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x360abb290fcf4116ULL;
  static const uint64_t static_value2 = 0x3977621351ecd430ULL;
};

template<class ContainerAllocator>
struct DataType< ::irp_sen_msgs::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irp_sen_msgs/encoder";
  }

  static const char* value(const ::irp_sen_msgs::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irp_sen_msgs::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header  # standard ROS message header\n"
"int64 type\n"
"int64 left_count\n"
"int64 right_count\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::irp_sen_msgs::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irp_sen_msgs::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.left_count);
      stream.next(m.right_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irp_sen_msgs::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irp_sen_msgs::encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.type);
    s << indent << "left_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_count);
    s << indent << "right_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRP_SEN_MSGS_MESSAGE_ENCODER_H
